"""Adding unique constraint ou users table

Revision ID: 089ad0840755
Revises: 4eb70880259f
Create Date: 2019-10-04 14:49:22.835423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089ad0840755'
down_revision = '4eb70880259f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
